.travis.yml, src/commands/run.js
This should pass the  --max-http-header-size=80000 to the nodeJs process. @drobnikj not sure if I put it on the right place.
=> increased nodeJs default header size.

README.md
The NPM version images load super slowly and make our tests on web/docs fail. Hoping this will help :)
=> Add lazy loading to the NPM version imgs

src/commands/push.js
The CLI was using the first item from the actor templates manifest.json when it could not find a matching template. This is confusing, especially because the manifest is handled in a completely different repo. So now it just uses some reasonable defaults.
=> fix: template-less push behaves unpredictably

npm-shrinkwrap.json, package.json, src/lib/utils.js
The source file format detection was not working for e.g. `.tgz` files, because their MIME type was not detected correctly.
I added the right MIME type definition for the `.tgz` files, but then I decided to fix one old TODO and rework the file format detection a bit.
Now if we can't detect the MIME type of the file, we don't automatically assume it to be text, but instead we try to detect its encoding from the contents, using the `isTextOrBinary` package.
It should be relatively fast, since:
- it's done only for files which couldn't be determined via MIME type
- it's done only when the total size of the pushed files is <3MB
- it reads only a few bytes in the start, middle and end of each file, not the whole file, and checks if they are in the Unicode characters range, or not
This should …
=> fix: improve source file format detection

src/commands/push.js
Or was this there on purpose? I remember someone was complaining about this on Slack, but I can't find the conversation.
=> chore: remove forgotten console.dir

.github/workflows/check.yml, .github/workflows/release.yml
~Doing any changes to `apify-cli` is a pain, because the tests keep failing if they're run in parallel. This makes them run serially, which takes longer, but at least you don't have to retry them.~ EDIT: turns out this does not help, so I reverted that part.
I also updated the `actions/xxx` versions to fix the warnings about Node 12 deprecations.
=> chore: update GitHub actions

src/commands/init.js
This makes sure that the `init` command also migrates apify.json if it's present. Otherwise it would create and empty `.actor/actor.json` file and `apify.json` would not be migrated.
=> feat: Add apify.json migration to init command

package.json
The node version in package.json is not consistent with node version in readme.
=> fix: Update node version

src/commands/create.js
When the actor prompt was looping around, it was a bit unintuitive to see that you've seen all possible templates, plus when some templates were wrapping, it was displaying a fragment of the wrapped template right under the question, making it look weird.
This disables the prompt looping, making it behave a bit better in general.
=> chore: Disable actor template prompt looping around

src/lib/version_check.js
In preparation for publishing the Apify CLI on Homebrew, this adds detection through which package manager was the CLI installed, and adjusts the update message to be correct for the given package manager.
=> feat: Print correct update command based on package manager

.github/workflows/release.yml, README.md, docs/installation.md
This:
- updates the docs to mention the possibility of installing the CLI via Homebrew
- calls the workflow to update the CLI version in the Homebrew formula in the `apify/homebrew-tap` repo once the new latest version is published
=> Prepare for release on Homebrew

src/commands/create.js, src/commands/run.js, src/lib/utils.js, src/lib/version_check.js
This PR adds two improvements to running the CLI on Homebrew:
- we now check the supported Node.js version based on `node --version`, not by `process.versions.node`
- this makes sure that if someone installs the CLI via Homebrew and does not have Node.js available globally, it shows him a nice error message rather than a weird error
- we now check where the symlink to the executable leads via `fs.realpathSync(...)`, not via `execSync('realpath ...')`
- this is because `realpath` is not available on macOS 12 and earlier by default, and also not in some Linux distributions
- also because why should we run an external command when the same thing is built in to Node.js
=> Improvements to Homebrew support

src/commands/create.js, src/lib/utils.js
NPM 7 deprecated the `--no-optional` argument and started recommending `--omit=optional` instead. This detects which NPM version is used, and uses the correct argument, so that this deprecation warning is not shown anymore:
=> Use correct "omit optional dependencies" argument based on NPM version

src/commands/create.js
Python actors require some post-create instructions:
- how to add additonal dependencies
- how to install Playwright and its browsers
This PR adds an option to have a post-create message in the template definition, and to show it after you run `apify create` with a specific template.
The accompanying PR in actor-templates is here: https://github.com/apify/actor-templates/pull/135
=> feat: Add a post-create message to Python actors

src/commands/push.js, src/lib/utils.js
Fixes https://github.com/apify/apify-core/issues/9403.
There was a bug that someone started a build from the CLI, the build spent too long in status `READY`, and the CLI logged "Build failed!" because the "is build running" condition didn't check for `READY`, just `RUNNING`.
This fixes it and improves the messages for each status we have.
=> Improve log messages for different build statuses

src/commands/push.js
Prompting user if want to open actor detail in browser after push
@dodaniel Feel free to update/suggest copy. Also, it can't be redirected to `actor source` as there's possibility to redirect to already created actor (which may be connected to git repository).
=> feat(app): Open actor detail after successful apify push

src/commands/login-new.js
I made a few small improvements to the `apify login-new` command:
- you can now choose right away whether you want to login through Console or by pasting the token
- this was based on internal feedback that people don't like browsers opening out of the blue
- it makes the prompt a bit more readable
- it works better if you use the CLI in Docker for example, where you don't have a browser installed
- I wrapped the `computerName()` call in a try/catch
- so that the CLI doesn't crash when you don't have `/usr/sbin` in $PATH on `macOS` (happens sometimes)
- I removed some debug logs to clean up the output
CC @mvolfik
=> feat: Improve `apify login-new` command

npm-shrinkwrap.json, package.json, src/commands/create.js
Fixes #356 
Consulted with @barjin, the adm-zip library is also used in fingerprint suite. This library doesn't support streaming decoding, but templates are small, so that shouldn't matter I hope.
(Switching from streaming to decoding one large blob would fix the bug with the original library as well, but let's switch anyways - we already use it on another project, and it seems to be maintained more recently.)
=> fix: use new library for extracting archives

.github/workflows/check.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml
This uses new secrets set on organization level instead of the repo-level secrets.
=> chore: Use new workflow secrets

package.json, src/lib/community.js
Closes apify/apify-web#2650
Partially implementing - there's no way to add custom `apify -h` content with older versions of oclif.
=> feat: add community message

src/bin/run
Right now, when you run a command (like `apify run`) and the command fails (perhaps because the actor failed), the exit code is still set to 0.
This was probably an oversight in some old version of `oclif`, the current version fixes it and exits with the right exit code now - https://github.com/oclif/core/blob/main/src/errors/handle.ts#L33. 
This changes our behavior to do the same.
=> fix: Use the right exit code on error

docs/reference.md
I tried to push the docs update directly to master, but is failed
https://github.com/apify/apify-cli/actions/runs/5275533425/jobs/9541117622
I think we can regenerate commands ref in docs as part of this npm command https://github.com/apify/apify-cli/blob/master/package.json#L11 to keep it updated
=> chore: fix docs reference

src/commands/pull.js
Closes #374.
Disable creating boolean-named folder
=> fix: folder path creation

src/commands/create.js, src/commands/init.js, src/lib/create-utils.js, src/lib/input_schema.js, src/lib/utils.js, test/commands/call.js, test/commands/create.js, test/commands/init.js, test/commands/run.js
```
{
"title": "PlaywrightCrawler Template",
"type": "object",
"schemaVersion": 1,
"properties": {
"startUrls": {
"title": "Start URLs",
"type": "array",
"description": "URLs to start with.",
"editor": "requestListSources",
"prefill": [
{
"url": "https://apify.com"
}
]
}
}
}
```
```
{
"startUrls": [
{
"url": "https://apify.com"
}
]
}
```
=> feat(create, init): create INPUT.json from input_schema prefills

.github/workflows/release.yaml
This sets up automatic updating of the `apify-cli` formula in the `homebrew/homebrew-core` repository.
It uses [`brew bump-formula-pr`](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) to create the update, the result looks like this: https://github.com/Homebrew/homebrew-core/pull/141010
@B4nan I've made it so that you and I are tagged in the PR with the update, so that we get notifications for replies from Homebrew maintainers.
=> feat: Auto-update `apify-cli` Homebrew formula in `homebrew-core`

src/commands/init.js
Adds Scrapy-related field to the telemetry data, if the project is wrapped via `apify init`. 
The usage through `apify init-wrap-scrapy` can be tracked through the use of the command.
=> refactor: track Scrapy wrapper usage using mixpanel

src/commands/run.js, src/lib/consts.js, src/lib/project_analyzer.js, src/lib/projects/CrawleeAnalyzer.js, src/lib/projects/OldApifySDKAnalyzer.js, src/lib/utils.js
This has been a pain and a half to work in, especially because no TS 😢 but that'll change soon 😏
Also adds in proper migration support to custom folders instead of a hardcoded folder for storages, full redirect of storages based on ENV variables, and a base for detecting old apify-based actors (who knows, maybe it'll be useful in the future)
Closes #373
=> chore: support new crawlee purge logic

docs/troubleshooting.md, website/sidebars.js
Recently, we deployed a bugged version where apify login would fail ([Slack thread](https://apifier.slack.com/archives/C0L33UM7Z/p1708169059446719)). 
We caught this internally but should this be first experienced by an external user, we want to provide them with some basic instructions on what to do.
=> docs: add a simple troubleshooting page with our contact

npm-shrinkwrap.json, package.json, src/lib/apify-oclif-help.js
Recently, we deployed a bugged version where apify login would fail ([Slack thread](https://apifier.slack.com/archives/C0L33UM7Z/p1708169059446719)).
We caught this internally but should this be first experienced by an external user, we want to provide them with some basic instructions on what to do.
This adds a new `TROUBLESHOOTING` section to the root help screen with the same content as was added in #484.
Note: The CLI was crashing when printing help with the latest oclif packages. So the original oclif packages were kept and a slightly older version of @oclif/core was installed.
=> feat: add a troubleshooting section to the root help screen

src/lib/exec.ts, src/lib/utils.ts, vitest.config.ts
Also gives windows higher timeouts and increases retries, since.. Windows is once again our unreliable entity
=> chore: don't print stdout at all when running tests

CONTRIBUTING.md, bin/dev.js, bin/dev.sh, package.json
I was trying to run the local copy of the CLI from a different folder, like `../apify-cli/bin/dev.js`, but unfortunately it didn't work, because the shebang in the `dev.js` file was resolved relative to the current working directory, instead of relative to the `apify-cli` folder.
This adds a `dev.sh` script, which will work when called from anywhere, and run `apify-cli/node_modules/.bin/tsx`. This allows you to test stuff like `apify create`, `apify pull` etc. easier.
=> chore: Update local dev script to allow running from anywhere

src/commands/run.ts
Forward-ports the bug fix for #535
=> fix: always enable crawlee storage purging when `--purge` is provided, even in non-crawlee-detected envs

src/commands/push.ts, src/lib/consts.ts, test/__setup__/hooks/useConsoleSpy.ts, test/__setup__/hooks/useTempPath.ts, test/commands/push.test.ts
Closes #317 
Do we want to maybe make the checks stricter? Should we only allow `push` from a directory that has a `.actor` folder / `actor.json` in it?
=> fix: prevent running `apify push` from non-actor-looking folders

package.json, src/commands/validate-schema.ts, src/hooks/deprecations.ts, test/commands/validate-schema.test.ts
=> fix: deprecate `vis` command in favor of `validate-schema`

src/lib/actor.ts, test/lib/actor.test.ts
But maybe we should allow users to force it to get local storages too?
Fix tested and adjusted from @netmilk's fork. it does work :pog:
Closes #270 
Closes #553
=> fix: always try to get a remote storage if IS_AT_HOME is true

cucumber.json, features/invalid-actor-json-output.feature.md, features/test-implementations/1.setup.ts, features/test-implementations/README.md, src/commands/init.ts, src/commands/pull.ts, src/commands/push.ts, src/commands/run.ts, src/lib/consts.ts, src/lib/utils.ts
Invalid actor.jsons will have their path printed out now
Closes #561
=> fix: print path to invalid `actor.json` when an invalid file is found

src/commands/actors/index.ts, src/commands/datasets/index.ts, src/commands/key-value-stores/index.ts, src/commands/request-queues/index.ts, src/commands/runs/index.ts
Prepares the following namespaces for commands:
- actors
- runs
- key-value-stores
- datasets
- request-queues
=> feat: bootstrap new command namespaces

src/commands/runs/abort.ts
Not sure if we should add in any more info tbh.. For `--json` it just returns the successful json of the aborting run
=> feat: `runs abort`

src/commands/actors/build.ts, src/commands/builds/create.ts
Easy alias
Also fixes `builds create` expecting the actor id as an _argument_ and not a flag.
=> feat: `actors build`

src/commands/actors/call.ts, src/commands/builds/create.ts, src/commands/builds/ls.ts, src/commands/push.ts, src/commands/runs/abort.ts, src/commands/runs/info.ts, src/commands/runs/log.ts, src/commands/runs/ls.ts, src/commands/runs/resurrect.ts, src/commands/task/run.ts, src/lib/commands/run-on-cloud.ts
- adds in a direct link to exporting the dataset url for `actors call` / `actors start` when it happens / `tasks run`
- moves most outputs to stdout for commands, keeping stderr mostly for actor run logs
- moves all `--actor=` to arguments instead
- remove `wait-for-finish` from `actors call`, as it now always waits for the run to finish (and `actors start` will immediately return the run)
=> chore: several tweaks 

src/lib/version_check.ts
Eventually maybe we should also check pnpm global/yarn global
=> feat: check if cli was installed using volta when checking for updates

src/lib/telemetry.ts
Part of apify/apify-web#4066
Similarly to the console, we want to distinguish among multiple sources of data for Mixpanel, thus setting `app` property to every tracking call.
=> chore: Setup cli app for Mixpanel

src/commands/key-value-stores/delete-value.ts, src/commands/key-value-stores/get-value.ts, src/commands/key-value-stores/keys.ts, src/commands/key-value-stores/set-value.ts
Adds in `keys` to list the keys, `set-value` to set a value and `delete-value` to delete a value
=> feat: key-value-store commands

src/commands/actors/info.ts
For some reason the existing code I had vanished from my OS :/, love it here.
So this is attempt 2, but it's almost back and almost fully implemented
Normal actor: 
PPR: 
PPE: 
Rental:
=> feat: `actors info`

package.json, src/commands/actor/push-data.ts, src/commands/datasets/get-items.ts, src/commands/datasets/push-items.ts, src/commands/run.ts, src/lib/commands/read-stdin.ts, src/lib/commands/resolve-input.ts, test/commands/call.test.ts, test/python_support.test.ts, yarn.lock
=> fix: handle stdin correctly from slower stdout emitting

src/commands/actors/ls.ts, src/commands/runs/ls.ts, src/lib/commands/responsive-table.ts, src/lib/utils.ts
Small terminals will now render the tables much more compact than before
When the full actor id is very long, and the user is on a small termianl, the runs column vanishes and a fully compact last run box appears
When there's enough space, that isn't the case
The time is also shown as relative, until a week passes, after which it is shown in full year-month-day format
On large terminals (>= 100 width), no changes have happened
=> refactor: more responsive output for `actors ls`

docs/index.md, website/versioned_docs/version-0.20/index.md, website/versioned_docs/version-0.21/index.md, website/versioned_docs/version-0.21/reference.md
remove github badges from next & versioned docs
change toc_max_heading_level for 0.21 version of docs
=> docs: remove gh badges

.github/workflows/check.yaml, .github/workflows/cucumber.yaml, src/commands/_register.ts, src/commands/run.ts, src/lib/command-framework/apify-command.ts, src/lib/command-framework/flags.ts, vitest.config.ts
Closes #590 
BREAKING CHANGE:
Purging in projects using Crawlee for SDK v3+ now purge by default, so using `--purge` flag is no longer necessary. Use `--no-purge` to keep the storage folder intact.
The `purge-queue`, `purge-dataset` and `purge-key-value-store` flags have been removed, and the logic of all three was combined into the `purge` flag.
=> feat: make storage purging default, add `--resurrect`

.github/workflows/check.yaml, .github/workflows/cucumber.yaml, .github/workflows/docs.yaml, .github/workflows/pre_release.yaml, .github/workflows/release.yaml
Should hopefully speed up template tests (since that seems to be the longest part of the CI). 
Also fixes the release flow tagging releases as `beta` - thankfully caught before we did an actual release
=> chore(ci): cache npm cache for tests

test/api/commands/log_in_out.test.ts, vitest.config.ts
Quick fix for login test that broke post telemetry change and increase unix timeouts too (which affects API tests specifically since creating and building actors takes annoyingly long)
=> chore: fix login/logout test + make vitest wait longer for api tests
