src/commands/push.js, test/commands/push.js
Should fix the issue with missing tarball url.
=> fix: Fix `apify-push` command

website/src/pages/index.js
Based on the Notion docs-v2 doc.
=> docs: landing page update

website/src/pages/index.js
=> docs: minor copy/links updates

.github/workflows/check.yml, .github/workflows/release.yml, package.json, test/python_support.js
This adds a basic test that the Python support in CLI works as expected.
Some more tests would be nice, but then I'd get too annoyed about the current state of the tests and I'd have to rewrite them all, so I'll save it for later 😄 
Closes #324.
=> Add automated tests for Python support

npm-shrinkwrap.json, package.json, src/lib/utils.js
I had this part of the code open so I decided to just fix the age old issue #72.
Closes #72
=> feat: Don't add `apify_storage` to .gitignore if it already is there

npm-shrinkwrap.json, package.json, src/commands/push.js
This is needed as it broke Crawlee e2e tests for platform 😅
=> feat(push): allow disabling of the prompt mechanism via flag/CI

npm-shrinkwrap.json, package.json, src/commands/run.js, src/lib/actor.js, src/lib/utils.js, test/commands/run.js
Only to be deployed after the worker change is deployed.
=> feat: Use actor/apify env vars instead of old `ENV_VARS`

src/commands/actor/push-data.js, src/commands/actor/set-value.js
=> fix: Add missing parent init call for push-data and set-value, it is causing unexpected error.

npm-shrinkwrap.json, package.json
How about we figure out some unified package release CI method... at least for the most popular packages? :)
=> chore: bump package version

README.md, docs/integrating-scrapy.md, npm-shrinkwrap.json, package.json, website/sidebars.js
Closes https://github.com/apify/actor-templates/issues/228
=> Add doc sub-page "Integrating Scrapy projects"

docs/index.md, docs/installation.md, docs/integrating-scrapy.md, website/src/pages/index.js
accidentally closes #447
closes https://github.com/apify/apify-core/issues/13587
=> docs: better guide for Scrapy migrations

docs/integrating-scrapy.md
- We don't capitalize headings
- Apify platform is with lowercase `p`
=> docs: Update capitalization integrating-scrapy.md

.gitignore, npm-shrinkwrap.json, package.json, test/.eslintrc.json, test/commands/call.js, test/commands/create.js, test/commands/info.js, test/commands/init.js, test/commands/log_in_out.js, test/commands/pull.js, test/commands/push.js, test/commands/run.js, test/commands/secrets/add.js, test/commands/secrets/rm.js, test/commands/vis.js, test/consts.js, test/python_support.js, test/secrets.js, test/templates.js, test/tsconfig.json, test/utils.js, test/version_check.js, vitest.config.ts
Needed for ESM migration (#460)
~~Also might speed up tests a lot 👀 need to see on CI~~ Well it seems to be around the same, maybe a wee bit faster. Would be faster if it could be parallelized, but the tests depend a _lot_ on being sequentially ran.
In the future, ideally the login would be ran only once as a setup, then we can stop dealing with logins per test that needs it 👀
=> chore: move from mocha to vitest

src/commands/create.js
Closes #459
Adding hint about apify push after template installation.
=> feat: extend success command on create

README.md, docs/reference.md, src/commands/call.js
"Act" is a mistake of the past...
=> docs: rename ACTID to ACTORID in "apify call"

.github/scripts/before-beta-release.ts, .github/workflows/check.yaml, vitest.config.ts
=> chore: fix ci script

.github/workflows/check.yaml, test/commands/secrets/add.test.ts, test/commands/secrets/rm.test.ts
The banes of 1 whole letter
Draft till Renovate finishes renovating
=> chore: fix CI again

package.json
Closes https://github.com/apify/apify-cli/issues/348
=> chore: regenerate website reference when releasing

src/commands/create.ts
Closes https://github.com/apify/apify-cli/issues/377
=> fix: prompt for new folder name when existing folder is used with `apify create`

.github/workflows/check.yaml
It doesn't really do what we expect anyways (and it might make CI for Windows more stable)
Narrator: It did not, in fact, help 😢 
Vlad: fine, I'll `--force` it through
Narrator: That did, in fact, work, but at what cost...
=> chore: force dependency installs on actions on Windows

src/commands/create.ts, test/commands/create.test.ts
=> feat: --no-optional for create command

bin/dev.js
Reported by @m-murasovs in DMs
=> refactor: dev script should import ts files

src/commands/run.ts
Closes #545 
Will push the same fix to the 0.19.x branch and release (I've tested it locally and it works as intended now)
=> fix: purge working in python again

docs/installation.md
I saw ppl struggling with orientation in the docs. Let's add a note to make it clear that initialization is not needed after `apify create`
=> docs: update installation.md

README.md, docs/index.md, docs/installation.md, docs/reference.md, docs/vars.md, src/commands/call.ts, src/commands/create.ts, src/commands/push.ts, src/lib/actor.ts, src/lib/utils.ts, test/__setup__/input-schemas/valid.json, test/commands/call.test.ts, test/commands/pull.test.ts, test/commands/push.test.ts, test/commands/run.test.ts
Related https://github.com/apify/apify-core/issues/11666
=> docs: `actor` -> `Actor`

docs/installation.md
Since some users were thinking you cannot install on windows for some reason.
=> docs: improve note about installation

bin/dev.js, bin/run.js, package.json, tsconfig.json, tsconfig.typechecking.json
=> fix: run scripts not printing unsupported node versions rightly

src/commands/call.ts, src/commands/run.ts, src/lib/apify_command.ts, src/lib/commands/read-stdin.ts, src/lib/commands/resolve-input.ts, src/lib/utils.ts, test/crawlee/commands/run.test.ts
=> fix: run command validating inputs caused inputs to not work in crawlee projects

.github/workflows/check.yaml, package.json
CI pains round 3, but the final breakage before it all just working:tm:
=> chore(release): v0.20.2

src/commands/call.ts, src/lib/commands/run-on-cloud.ts
=> feat: printing dataset result for `call` command

.github/workflows/check.yaml
I haven't been involved in the Homebrew releases for quite a while, so no need to tag me anymore.
=> chore: don't tag fnesveda on new Homebrew releases

website/package.json, website/yarn.lock
Bumps the Docusaurus (and all the dependencies) to `docusaurus@v3`-compliant versions.
=> docs: bump Docusaurus@v3

src/commands/run.ts, src/lib/input_schema.ts, test/commands/run.test.ts
=> fix: auto-set `apify run` `INPUT.json` only with values that have defaults

src/commands/runs/resurrect.ts
=> feat: `runs resurrect`

src/lib/input_schema.ts
=> fix: look for lowercase input schema in default paths

src/commands/actors/rm.ts, src/commands/builds/info.ts, src/commands/builds/rm.ts, src/commands/runs/rm.ts, src/lib/commands/confirm.ts
=> feat: `runs rm` & `builds rm` & `actors rm`

src/commands/actors/call.ts, src/commands/actors/start.ts
=> feat: `actors start`

src/commands/key-value-stores/get-value.ts, src/commands/key-value-stores/index.ts, src/lib/utils.ts, tsconfig.json
=> feat: `key-value-stores get-value`

.github/workflows/pre_release.yaml
=> chore(ci): fix formatting script

src/commands/actors/call.ts
=> fix: emit logs to stderr when actors are started with `--json` flag

.github/workflows/release.yaml, CHANGELOG.md, README.md, docs/reference.md, package.json
Also reverts the pseudo-release that was 0.21.1 as it didn't fully work)
=> chore(ci): fix release flow

package.json, src/commands/actor/get-public-url.ts, src/lib/consts.ts, yarn.lock
This PR is part of https://github.com/apify/apify-core/issues/19363, which updates `KeyValueStore.getPublicUrl(recordKey)` to generate signed links using HMAC.
This PR:
- adds signature to actor get-public-url to Apify CLI
=> feat: add signature to actor get-public-url

docs/reference.md, website/versioned_docs/version-0.21/reference.md
last small PR before releasing 0.21.4
=> chore: docs fix

package.json, src/lib/exec.ts, src/lib/hooks/runtimes/javascript.ts, src/lib/hooks/runtimes/python.ts, src/lib/hooks/runtimes/utils.ts
Somehow not encountered in CI 🙃
=> fix: runtime detection on Windows

src/commands/run.ts, src/lib/hooks/useCwdProject.ts, test/fixtures/commands/run/python/python-scrapy-template-works.test.ts
Closes https://github.com/apify/apify-cli/issues/796
=> fix: Non-"migrated" scrapy not working anymore

src/entrypoints/_shared.ts
As reported by @barjin 
New look
=> fix: pretty message for invalid choices

.github/scripts/before-beta-release.ts, .github/workflows/pre_release.yaml, .github/workflows/release.yaml, package.json, tsconfig.eslint.json
Wouldn't be a PR that affects CI without issues 🫠  (forgot to update pattern for tests and apparently npm is too aggressive with devEngines support)
=> chore: fix release and pre-release ci

src/commands/actors/pull.ts, test/api/commands/pull.test.ts
Closes #855 
Won't backport since v1 is so close to release
=> fix(pull): handle private actors correctly

scripts/install/install.sh, src/commands/cli-management/install.ts, src/entrypoints/_shared.ts
Also small aesthetic change for install script
=> chore: fix node:util parseArgs migration
